statements

statements := statements statement
statements := statement
statements __EPSILON__

statement := expr

lvalue := IDENTIFIER
lvalue := lvalue . IDENTIFIER

expr := asgn_expr

asgn_expr := lvalue = asgn_expr
asgn_expr := add_expr

add_expr := add_expr + mult_expr
add_expr := add_expr - mult_expr
add_expr := mult_expr

mult_expr := mult_expr * prim_expr
mult_expr := mult_expr / prim_expr
mult_expr := prim_expr

prim_expr := IDENTIFIER
prim_expr := NUMBER_CONST
prim_expr := ( expr )