Statements

Statements := Statements Statement
Statements __EPSILON__

Statement := PrintStmt
Statement := Expression ;

// Control statements

// Commands

PrintStmt := PRINT Expression
PrintStmt := PRINTLN Expression

// Names and types

Name := IDENTIFIER
Name := Name . IDENTIFIER

Type := IDENTIFIER
Type := Type :: IDENTIFIER
Type := Type TemplateArgs

// Templates

TemplateArgs := < TemplateArgList >

TemplateArgList := TemplateArgList , TemplateArg
TemplateArgList := TemplateArg

TemplateArg := Literal
TemplateArg := Type

// Expressions

lvalue := Name
lvalue := AssignmentExpression

Literal := INT_LITERAL
Literal := FLOAT_LITERAL
Literal := STRING_LITERAL

PrimaryExpression := Literal
PrimaryExpression := Name
PrimaryExpression := ParenthesizedExpression

ParenthesizedExpression := ( Expression )

AdditiveOperator := +
AdditiveOperator := -

AdditiveExpression := AdditiveExpression AdditiveOperator PrimaryExpression
AdditiveExpression := PrimaryExpression

AssignmentOperator := =
AssignmentOperator := +=
AssignmentOperator := -=

AssignmentExpression := lvalue AssignmentOperator AdditiveExpression

Expression := AssignmentExpression
Expression := AdditiveExpression