#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

extern "C" {
/*
 * Class:     compiler_jevm_NativeVM
 * Method:    execute
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_compiler_jevm_NativeVM_execute
        (JNIEnv *, jobject, jbyteArray);
}